using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using RoslynMcp.Core.FileSystem;

namespace RoslynMcp.Core.Workspace;

/// <summary>
/// Materializes a real <c>.csproj</c> for a standalone C# file (a .NET 10 "file-based
/// program", with or without <c>#:</c> directives) so it can be loaded through the normal
/// <see cref="Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace"/> pipeline.
/// </summary>
/// <remarks>
/// The project is generated by the SDK itself: we invoke <c>dotnet run-api</c> — the same
/// mechanism Roslyn's own language server uses — which returns the exact virtual-project
/// XML the SDK would build (resolved <c>#:sdk</c>/<c>#:package</c>/<c>#:project</c>/<c>#:property</c>,
/// the <c>FileBasedProgram</c> feature, default props, and the SDK's default analyzers and
/// source generators). We then make the <c>#:project</c> references absolute and write the
/// project to a temp directory, so nothing is written into the user's source tree. Because
/// the referenced projects are opened at their real on-disk locations, they still inherit
/// their own <c>Directory.Build.props</c>; only the thin wrapper project does not (the
/// accepted trade-off of not materializing in-place).
/// </remarks>
internal static class FileBasedProgramProject
{
    /// <summary>A materialized file-based program ready to hand to MSBuildWorkspace.</summary>
    internal sealed record Materialized(string CsprojPath, string DirectiveSignature);

    public static async Task<Materialized?> MaterializeAsync(
        string entryFilePath,
        TimeSpan timeout,
        Action<string>? log,
        Action<string, Exception?>? logError,
        CancellationToken cancellationToken)
    {
        var normalizedEntry = PathResolver.NormalizePath(entryFilePath);
        var entryDir = Path.GetDirectoryName(normalizedEntry);
        if (string.IsNullOrEmpty(entryDir)) return null;

        var signature = await ComputeDirectiveSignatureAsync(normalizedEntry, cancellationToken);

        string projectXml;
        try
        {
            log?.Invoke($"Asking 'dotnet run-api' for the file-based project of: {normalizedEntry}");
            var request = JsonSerializer.Serialize(new Dictionary<string, string>
            {
                ["$type"] = "GetProject",
                ["EntryPointFileFullPath"] = normalizedEntry,
            });

            var (exitCode, stdout, stderr) = await RunDotnetAsync(
                ["run-api"], entryDir, request, timeout, cancellationToken);

            projectXml = ExtractProjectXml(stdout, log);
            if (string.IsNullOrEmpty(projectXml))
            {
                logError?.Invoke(
                    $"'dotnet run-api' did not return a project for '{normalizedEntry}' (exit {exitCode}). {Trim(stderr)}",
                    null);
                return null;
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            logError?.Invoke($"'dotnet run-api' failed for '{normalizedEntry}'.", ex);
            return null;
        }

        // Make #:project / #:ref references absolute so the project is location-independent,
        // then write it to a deterministic temp directory (never into the user's tree).
        var rewritten = MakeReferencesAbsolute(projectXml, entryDir);
        var csprojPath = GetTempProjectPath(normalizedEntry);
        Directory.CreateDirectory(Path.GetDirectoryName(csprojPath)!);
        await File.WriteAllTextAsync(csprojPath, rewritten, cancellationToken);

        // MSBuildWorkspace.OpenProjectAsync needs the project restored (and its referenced
        // projects, which restore reaches transitively). Tolerate a non-zero exit — Roslyn
        // works with partial results, and the diagnostics will explain anything missing.
        try
        {
            var (restoreExit, _, restoreErr) = await RunDotnetAsync(
                ["restore", csprojPath], Path.GetDirectoryName(csprojPath)!, stdin: null, timeout, cancellationToken);
            if (restoreExit != 0)
                log?.Invoke($"restore of file-based project exited {restoreExit}: {Trim(restoreErr)}");
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            logError?.Invoke($"restore of file-based project '{csprojPath}' failed.", ex);
        }

        log?.Invoke($"Materialized file-based project at: {csprojPath}");
        return new Materialized(csprojPath, signature);
    }

    /// <summary>
    /// A stable fingerprint of a file's leading <c>#:</c> directives. When this changes
    /// between edits, the resolved project (references, SDK, properties) may have changed and
    /// the workspace must be rebuilt rather than incrementally text-updated.
    /// </summary>
    public static string ComputeDirectiveSignature(string text)
    {
        var builder = new StringBuilder();
        var inBlockComment = false;
        foreach (var rawLine in EnumerateLines(text))
        {
            var trimmed = rawLine.Trim();
            if (inBlockComment)
            {
                if (trimmed.Contains("*/", StringComparison.Ordinal)) inBlockComment = false;
                continue;
            }
            if (trimmed.Length == 0) continue;
            if (trimmed.StartsWith("#:", StringComparison.Ordinal)) { builder.Append(trimmed).Append('\n'); continue; }
            if (trimmed.StartsWith("#!", StringComparison.Ordinal)) continue;       // shebang
            if (trimmed.StartsWith("//", StringComparison.Ordinal)) continue;       // line comment
            if (trimmed.StartsWith("/*", StringComparison.Ordinal))                 // block comment
            {
                if (!trimmed.Contains("*/", StringComparison.Ordinal)) inBlockComment = true;
                continue;
            }
            break; // first real token: directives can no longer appear
        }
        return builder.ToString();
    }

    private static async Task<string> ComputeDirectiveSignatureAsync(string filePath, CancellationToken ct)
    {
        try
        {
            using var stream = new FileStream(
                filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
            using var reader = new StreamReader(stream);
            return ComputeDirectiveSignature(await reader.ReadToEndAsync(ct));
        }
        catch (OperationCanceledException) { throw; }
        catch { return string.Empty; }
    }

    private static IEnumerable<string> EnumerateLines(string text)
    {
        using var reader = new StringReader(text);
        string? line;
        var scanned = 0;
        while ((line = reader.ReadLine()) != null && scanned++ < 500)
            yield return line;
    }

    private static string ExtractProjectXml(string stdout, Action<string>? log)
    {
        if (string.IsNullOrWhiteSpace(stdout)) return "";
        var start = stdout.IndexOf('{');
        if (start < 0) return "";
        try
        {
            using var doc = JsonDocument.Parse(stdout[start..]);
            var root = doc.RootElement;
            var type = root.TryGetProperty("$type", out var t) ? t.GetString() : null;

            if (root.TryGetProperty("Diagnostics", out var diags) && diags.ValueKind == JsonValueKind.Array)
                foreach (var d in diags.EnumerateArray())
                    log?.Invoke($"run-api directive diagnostic: {d}");

            if (!string.Equals(type, "Project", StringComparison.Ordinal))
            {
                var message = root.TryGetProperty("Message", out var m) ? m.GetString() : type;
                log?.Invoke($"run-api returned '{type}': {message}");
                return "";
            }

            return root.TryGetProperty("Content", out var content) ? content.GetString() ?? "" : "";
        }
        catch (JsonException)
        {
            return "";
        }
    }

    /// <summary>
    /// Rewrites relative <c>ProjectReference</c>/<c>Reference</c> <c>Include</c> paths to
    /// absolute, resolved against the entry file's directory (the SDK emits them relative to
    /// it). Leaves SDK imports and already-absolute paths untouched.
    /// </summary>
    private static string MakeReferencesAbsolute(string projectXml, string entryDir)
    {
        XDocument doc;
        try { doc = XDocument.Parse(projectXml, LoadOptions.PreserveWhitespace); }
        catch (System.Xml.XmlException) { return projectXml; }

        foreach (var element in doc.Descendants())
        {
            if (element.Name.LocalName is not ("ProjectReference" or "Reference")) continue;
            var include = element.Attribute("Include")?.Value;
            if (string.IsNullOrEmpty(include) || Path.IsPathRooted(include)) continue;
            var absolute = PathResolver.NormalizePath(Path.Combine(entryDir, include.Replace('\\', '/')));
            element.SetAttributeValue("Include", absolute);
        }

        return doc.ToString(SaveOptions.DisableFormatting);
    }

    /// <summary>
    /// A deterministic temp path (outside the user's tree) for the materialized project,
    /// keyed by the entry file's full path so repeated loads reuse the same restored project.
    /// </summary>
    private static string GetTempProjectPath(string normalizedEntry)
    {
        var hash = Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(normalizedEntry.ToUpperInvariant())))[..16].ToLowerInvariant();
        var name = Path.GetFileNameWithoutExtension(normalizedEntry);
        if (string.IsNullOrEmpty(name)) name = "Standalone";
        return Path.Combine(Path.GetTempPath(), "roslynmcp", "filebased", $"{name}-{hash}", $"{name}.csproj");
    }

    private static async Task<(int ExitCode, string StdOut, string StdErr)> RunDotnetAsync(
        string[] args, string workingDir, string? stdin, TimeSpan timeout, CancellationToken ct)
    {
        var psi = new ProcessStartInfo("dotnet")
        {
            WorkingDirectory = workingDir,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            RedirectStandardInput = stdin is not null,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (var arg in args) psi.ArgumentList.Add(arg);

        using var process = new Process { StartInfo = psi };
        process.Start();

        using var timeoutCts = new CancellationTokenSource(timeout);
        using var linked = CancellationTokenSource.CreateLinkedTokenSource(ct, timeoutCts.Token);

        try
        {
            if (stdin is not null)
            {
                await process.StandardInput.WriteAsync(stdin.AsMemory(), linked.Token);
                process.StandardInput.Close();
            }
            var stdoutTask = process.StandardOutput.ReadToEndAsync(linked.Token);
            var stderrTask = process.StandardError.ReadToEndAsync(linked.Token);
            await process.WaitForExitAsync(linked.Token);
            return (process.ExitCode, await stdoutTask, await stderrTask);
        }
        catch (OperationCanceledException)
        {
            try { if (!process.HasExited) process.Kill(entireProcessTree: true); }
            catch { /* best effort */ }
            throw;
        }
    }

    private static string Trim(string? s)
        => string.IsNullOrWhiteSpace(s) ? "" : s.Trim().Replace('\n', ' ').Replace('\r', ' ');
}
