using System.Diagnostics;
using System.Text;
using System.Text.Json;
using RoslynMcp.Core.FileSystem;

namespace RoslynMcp.Core.Workspace;

/// <summary>
/// Materializes a real <c>.csproj</c> for a standalone C# file (a .NET 10 "file-based
/// program", with or without <c>#:</c> directives) so it can be loaded through the normal
/// <see cref="Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace"/> pipeline.
/// </summary>
/// <remarks>
/// The project is generated by the SDK itself: we invoke <c>dotnet run-api</c> — the same
/// mechanism Roslyn's own language server uses — which returns the exact virtual-project XML
/// the SDK would build. We write that XML <b>verbatim</b> to <c>&lt;entry&gt;.cs.csproj</c>
/// <b>in the entry file's own directory</b> (the path the SDK/LSP use) and open it with the
/// public <c>MSBuildWorkspace.OpenProjectAsync</c>.
/// <para>
/// Evaluating in place is what makes this faithful: MSBuild's <c>$(MSBuildProjectDirectory)</c>
/// becomes the entry file's directory, so every location-dependent behavior resolves exactly
/// as <c>dotnet run</c> does — <c>Directory.Build.props</c>/<c>.targets</c>, <c>global.json</c>,
/// <c>Directory.Packages.props</c>, <c>NuGet.config</c>, and <c>#:project</c> relative paths —
/// by construction, with no patching. The Roslyn LSP achieves the same by handing the XML and
/// this path to an internal build-host API that never writes a file; that API isn't public, so
/// we write a real file and remove it again after the project is loaded (see the provider).
/// </para>
/// <para>
/// Because the file lives in the user's tree (briefly), we first register <c>*.cs.csproj</c>
/// in the repo's local <c>.git/info/exclude</c> — best-effort, so git never stages it and no
/// tracked <c>.gitignore</c> is touched.
/// </para>
/// </remarks>
internal static class FileBasedProgramProject
{
    /// <summary>Glob that matches every file-based-program wrapper; one entry covers all of them.</summary>
    private const string GitExcludePattern = "*.cs.csproj";

    /// <summary>A materialized file-based program ready to hand to MSBuildWorkspace.</summary>
    internal sealed record Materialized(string CsprojPath, string DirectiveSignature);

    public static async Task<Materialized?> MaterializeAsync(
        string entryFilePath,
        TimeSpan timeout,
        Action<string>? log,
        Action<string, Exception?>? logError,
        CancellationToken cancellationToken)
    {
        var normalizedEntry = PathResolver.NormalizePath(entryFilePath);
        var entryDir = Path.GetDirectoryName(normalizedEntry);
        if (string.IsNullOrEmpty(entryDir)) return null;

        var signature = await ComputeDirectiveSignatureAsync(normalizedEntry, cancellationToken);

        string projectXml;
        string? projectPath;
        try
        {
            log?.Invoke($"Asking 'dotnet run-api' for the file-based project of: {normalizedEntry}");
            var request = JsonSerializer.Serialize(new Dictionary<string, string>
            {
                ["$type"] = "GetProject",
                ["EntryPointFileFullPath"] = normalizedEntry,
            });

            var (exitCode, stdout, stderr) = await RunProcessAsync(
                "dotnet", ["run-api"], entryDir, request, timeout, cancellationToken);

            (projectXml, projectPath) = ExtractProject(stdout, log);
            if (string.IsNullOrEmpty(projectXml))
            {
                logError?.Invoke(
                    $"'dotnet run-api' did not return a project for '{normalizedEntry}' (exit {exitCode}). {Trim(stderr)}",
                    null);
                return null;
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            logError?.Invoke($"'dotnet run-api' failed for '{normalizedEntry}'.", ex);
            return null;
        }

        // The SDK's virtual project path is <entry>.cs.csproj in the entry file's directory.
        var csprojPath = !string.IsNullOrEmpty(projectPath)
            ? PathResolver.NormalizePath(projectPath)
            : normalizedEntry + ".csproj";

        // Register the ignore BEFORE the file exists, so git never has a window to stage it.
        await EnsureGitIgnoredBestEffortAsync(entryDir, timeout, log, cancellationToken);

        // Write the SDK XML verbatim, in place. (Overwrites any stale leftover from a crash.)
        await File.WriteAllTextAsync(csprojPath, projectXml, cancellationToken);

        // MSBuildWorkspace.OpenProjectAsync needs the project restored (and its referenced
        // projects, which restore reaches transitively). Tolerate a non-zero exit — Roslyn
        // works with partial results, and the diagnostics will explain anything missing.
        try
        {
            var (restoreExit, _, restoreErr) = await RunProcessAsync(
                "dotnet", ["restore", csprojPath], entryDir, stdin: null, timeout, cancellationToken);
            if (restoreExit != 0)
                log?.Invoke($"restore of file-based project exited {restoreExit}: {Trim(restoreErr)}");
        }
        catch (OperationCanceledException)
        {
            TryDeleteFile(csprojPath);
            throw;
        }
        catch (Exception ex)
        {
            logError?.Invoke($"restore of file-based project '{csprojPath}' failed.", ex);
        }

        log?.Invoke($"Materialized file-based project (in place) at: {csprojPath}");
        return new Materialized(csprojPath, signature);
    }

    /// <summary>Deletes a materialized wrapper project; never throws. Used by the provider once
    /// the project is loaded into the workspace (the in-memory solution no longer needs it).</summary>
    public static void TryDeleteFile(string path)
    {
        try { if (File.Exists(path)) File.Delete(path); }
        catch { /* best-effort cleanup */ }
    }

    /// <summary>
    /// Best-effort registration of <see cref="GitExcludePattern"/> in the repo's local
    /// <c>.git/info/exclude</c> so the transient wrapper projects stay untracked, without
    /// touching any committed <c>.gitignore</c>. Never throws and never blocks loading:
    /// if the entry isn't in a git repo, git is unavailable, or the file can't be read/written
    /// safely, it is simply skipped. A single glob covers every wrapper, so concurrent loads
    /// converge (at worst a harmless duplicate line) — there is no per-file bookkeeping to race on.
    /// </summary>
    private static async Task EnsureGitIgnoredBestEffortAsync(
        string entryDir, TimeSpan timeout, Action<string>? log, CancellationToken ct)
    {
        try
        {
            var (exit, stdout, _) = await RunProcessAsync(
                "git", ["-C", entryDir, "rev-parse", "--git-path", "info/exclude"], entryDir, null, timeout, ct);
            if (exit != 0) return; // not a git work tree, or git not installed

            var reported = stdout.Trim();
            if (reported.Length == 0) return;
            var excludePath = Path.IsPathRooted(reported)
                ? reported
                : Path.GetFullPath(Path.Combine(entryDir, reported));

            if (File.Exists(excludePath))
            {
                foreach (var line in await File.ReadAllLinesAsync(excludePath, ct))
                    if (line.Trim().Equals(GitExcludePattern, StringComparison.Ordinal))
                        return; // already excluded
            }
            else
            {
                var dir = Path.GetDirectoryName(excludePath);
                if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
            }

            // Appending a single short line is the least corruption-prone write; a concurrent
            // racer at worst adds a second identical line, which git ignores.
            await File.AppendAllTextAsync(excludePath, GitExcludePattern + "\n", ct);
            log?.Invoke($"Excluded '{GitExcludePattern}' via {excludePath}.");
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch
        {
            // Best-effort only: never let ignore bookkeeping break or corrupt anything.
        }
    }

    /// <summary>
    /// A stable fingerprint of a file's leading <c>#:</c> directives. When this changes
    /// between edits, the resolved project (references, SDK, properties) may have changed and
    /// the workspace must be rebuilt rather than incrementally text-updated.
    /// </summary>
    public static string ComputeDirectiveSignature(string text)
    {
        var builder = new StringBuilder();
        var inBlockComment = false;
        foreach (var rawLine in EnumerateLines(text))
        {
            var trimmed = rawLine.Trim();
            if (inBlockComment)
            {
                if (trimmed.Contains("*/", StringComparison.Ordinal)) inBlockComment = false;
                continue;
            }
            if (trimmed.Length == 0) continue;
            if (trimmed.StartsWith("#:", StringComparison.Ordinal)) { builder.Append(trimmed).Append('\n'); continue; }
            if (trimmed.StartsWith("#!", StringComparison.Ordinal)) continue;       // shebang
            if (trimmed.StartsWith("//", StringComparison.Ordinal)) continue;       // line comment
            if (trimmed.StartsWith("/*", StringComparison.Ordinal))                 // block comment
            {
                if (!trimmed.Contains("*/", StringComparison.Ordinal)) inBlockComment = true;
                continue;
            }
            break; // first real token: directives can no longer appear
        }
        return builder.ToString();
    }

    private static async Task<string> ComputeDirectiveSignatureAsync(string filePath, CancellationToken ct)
    {
        try
        {
            using var stream = new FileStream(
                filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
            using var reader = new StreamReader(stream);
            return ComputeDirectiveSignature(await reader.ReadToEndAsync(ct));
        }
        catch (OperationCanceledException) { throw; }
        catch { return string.Empty; }
    }

    private static IEnumerable<string> EnumerateLines(string text)
    {
        using var reader = new StringReader(text);
        string? line;
        var scanned = 0;
        while ((line = reader.ReadLine()) != null && scanned++ < 500)
            yield return line;
    }

    /// <summary>Parses the <c>run-api GetProject</c> response, returning the project XML
    /// (<c>Content</c>) and its intended path (<c>ProjectPath</c>), or empty on any error.</summary>
    private static (string Content, string? ProjectPath) ExtractProject(string stdout, Action<string>? log)
    {
        if (string.IsNullOrWhiteSpace(stdout)) return ("", null);
        var start = stdout.IndexOf('{');
        if (start < 0) return ("", null);
        try
        {
            using var doc = JsonDocument.Parse(stdout[start..]);
            var root = doc.RootElement;
            var type = root.TryGetProperty("$type", out var t) ? t.GetString() : null;

            if (root.TryGetProperty("Diagnostics", out var diags) && diags.ValueKind == JsonValueKind.Array)
                foreach (var d in diags.EnumerateArray())
                    log?.Invoke($"run-api directive diagnostic: {d}");

            if (!string.Equals(type, "Project", StringComparison.Ordinal))
            {
                var message = root.TryGetProperty("Message", out var m) ? m.GetString() : type;
                log?.Invoke($"run-api returned '{type}': {message}");
                return ("", null);
            }

            var content = root.TryGetProperty("Content", out var c) ? c.GetString() ?? "" : "";
            var path = root.TryGetProperty("ProjectPath", out var p) ? p.GetString() : null;
            return (content, path);
        }
        catch (JsonException)
        {
            return ("", null);
        }
    }

    private static async Task<(int ExitCode, string StdOut, string StdErr)> RunProcessAsync(
        string fileName, string[] args, string workingDir, string? stdin, TimeSpan timeout, CancellationToken ct)
    {
        var psi = new ProcessStartInfo(fileName)
        {
            WorkingDirectory = workingDir,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            RedirectStandardInput = stdin is not null,
            UseShellExecute = false,
            CreateNoWindow = true,
        };
        foreach (var arg in args) psi.ArgumentList.Add(arg);

        using var process = new Process { StartInfo = psi };
        process.Start();

        using var timeoutCts = new CancellationTokenSource(timeout);
        using var linked = CancellationTokenSource.CreateLinkedTokenSource(ct, timeoutCts.Token);

        try
        {
            if (stdin is not null)
            {
                await process.StandardInput.WriteAsync(stdin.AsMemory(), linked.Token);
                process.StandardInput.Close();
            }
            var stdoutTask = process.StandardOutput.ReadToEndAsync(linked.Token);
            var stderrTask = process.StandardError.ReadToEndAsync(linked.Token);
            await process.WaitForExitAsync(linked.Token);
            return (process.ExitCode, await stdoutTask, await stderrTask);
        }
        catch (OperationCanceledException)
        {
            try { if (!process.HasExited) process.Kill(entireProcessTree: true); }
            catch { /* best effort */ }
            throw;
        }
    }

    private static string Trim(string? s)
        => string.IsNullOrWhiteSpace(s) ? "" : s.Trim().Replace('\n', ' ').Replace('\r', ' ');
}
